export const CAR_REPOSITORY = 'CAR_REPOSITORY'
export const CAR_DETAILS_REPOSITORY = 'CAR_DETAILS_REPOSITORY'
export const CAR_SPECIFICATION_REPOSITORY = 'CAR_SPECIFICATION_REPOSITORY'
export const CAR_IMAGE_REPOSITORY = 'CAR_IMAGE_REPOSITORY'